server:
  port: 8080

spring:
  application:
    name: config-client
  config:
    import: "configserver:http://localhost:8888" # Apontando para o Config Server

management:
  endpoints:
    web:
      exposure:
        include: refresh, health  # Expondo os endpoints 'refresh' e 'health'